In [309]:
import numpy as np
from numpy.linalg import inv
np.set_printoptions ( precision = 2)

In [310]:
def collapse_m ( m ):
    m2 = np.eye ( 3 )
    m2 [ 0:3 , 0:3 ] = m [ 0:3 , [ 0 , 1 , 3] ]
    return m2

def collapse_v ( v ):
    #return v [ [ 0 , 1 , 3 ]]
    return v [ 0 : 3 ]

def create_matrix (theta=None):
    M = np.eye ( 4 )
    M [ 0 , 3] = ( np.random.random ( ) - 0.5 ) * 10
    M [ 1 , 3] = ( np.random.random ( ) - 0.5 ) * 10
    M [ 2 , 3 ]= ( np.random.random ( ) - 0.5 ) * 10
    if theta == None:
        theta = np.random.random ( ) * 2 * np.pi
    ##Rotate about Z
    M [ 1 ,1 ] = np.cos ( theta )
    M [ 2 ,2 ] = np.cos ( theta )
    M [ 1 ,2 ] = -np.sin ( theta )
    M [ 2 ,1 ] = np.sin ( theta )
    return M
def create_point ( ):
    v = ( np.random.random ( 4 ) - 0.5 ) * 10
    #v [ 2 ] = 0
    v [ 3 ] = 1
    return v

def normalize ( v ):
    return v / v [ 2 ]
create_matrix()
create_vector ()
collapse_m ( create_matrix ())

array([[ 1.  ,  0.  , -3.96],
       [ 0.  ,  0.25,  3.53],
       [ 0.  , -0.97,  0.58]])

In [311]:
Hw1 = create_matrix (theta = np.pi/7) 
Hw2 = create_matrix (theta = np.pi/2)

#H21 = np.dot ( Hw1 , inv ( Hw2 ) )

Pw = create_point ( )

Pw [ 2 ] = 0
Pwx = collapse_v ( np.copy ( Pw ) )
Pwx [2 ] = 1


P1 = np.dot ( Hw1 , Pw )
P1x  = collapse_v ( P1 )

P2 = np.dot ( Hw2 , Pw )
P2x  = collapse_v ( P2 )
print Hw1
print Hw2
print Pw , Pwx
print P1 , P1x
print P2 , P2x

[[ 1.    0.    0.   -3.06]
 [ 0.    0.9  -0.43 -3.9 ]
 [ 0.    0.43  0.9   1.26]
 [ 0.    0.    0.    1.  ]]
[[  1.00e+00   0.00e+00   0.00e+00  -2.54e+00]
 [  0.00e+00   6.12e-17  -1.00e+00   1.52e+00]
 [  0.00e+00   1.00e+00   6.12e-17   3.91e+00]
 [  0.00e+00   0.00e+00   0.00e+00   1.00e+00]]
[ 2.54  1.49  0.    1.  ] [ 2.54  1.49  1.  ]
[-0.52 -2.56  1.91  1.  ] [-0.52 -2.56  1.91]
[  4.67e-03   1.52e+00   5.40e+00   1.00e+00] [  4.67e-03   1.52e+00   5.40e+00]


In [312]:
Hw1x = collapse_m (Hw1 ) #maps 2d Pw to p1
#Hw1x = Hw1x / Hw1x [ 2 ] [ 2 ]
Hw2x = collapse_m (Hw2)   #maps 2d 
#Hw2x = Hw2x / Hw2x [ 2 ] [ 2 ]
print Hw1x
print Hw2x

[[ 1.    0.   -3.06]
 [ 0.    0.9  -3.9 ]
 [ 0.    0.43  1.26]]
[[  1.00e+00   0.00e+00  -2.54e+00]
 [  0.00e+00   6.12e-17   1.52e+00]
 [  0.00e+00   1.00e+00   3.91e+00]]


In [313]:
print Pw
print Pwx
#print np.dot ( Hw1 , Pw) # Pw in frame 1
print P1x
print np.dot ( Hw1x , Pwx ) # so Hw1x maps a  x y homogeneous in world frame to frame 1
print '########'
print Pwx , np.dot ( inv ( Hw1x ) , P1x )
#P1x = Hw1x Pwx , Pwx = inv ( Hw1x ) P1x
print '########'
print Pwx , np.dot ( inv ( Hw2x ) , P2x )
#P2x = Hw2x Pwx , Pwx = inv ( Hw2x ) P2x
print '########'
print P1x , np.dot ( Hw1x , np.dot ( inv ( Hw2x ) , P2x ) )
#P1x = Hw1x H2wx P2x

[ 2.54  1.49  0.    1.  ]
[ 2.54  1.49  1.  ]
[-0.52 -2.56  1.91]
[-0.52 -2.56  1.91]
########
[ 2.54  1.49  1.  ] [ 2.54  1.49  1.  ]
########
[ 2.54  1.49  1.  ] [ 2.54  1.49  1.  ]
########
[-0.52 -2.56  1.91] [-0.52 -2.56  1.91]
